apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  labels:
    app-name: grpc-client
spec:
  selector:
    matchLabels:
      app-name: grpc-client
  template:
    metadata:
      labels:
        app-name: grpc-client
      name: grpc-client
    spec:
      containers:
        - command:
            - client
          args:
            - --address
            - grpc-server-service.default.svc.cluster.local:8088
          env:
            - name: GRPC_GO_RETRY
              value: "on"
          image: docker.io/leoshus/grpc-demo:v6
          imagePullPolicy: Always
          name: client
          resources:
            limits:
              cpu: "0.5"
              memory: 100Mi
            requests:
              cpu: "0.5"
              memory: 100Mi
      restartPolicy: Always

